import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiOutlineMail} from 'react-icons/ai' 
import {FaLinkedinIn } from 'react-icons/fa'
import {DiGithubAlt} from 'react-icons/di'
import Image from "next/image"
import avatar from "../public/avatar.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'

export default function Home() {
    const[darkMode, setDarkMode] = useState(true)
    return (
        <div className={darkMode ? 'dark' : ''}>
            <Head>
                <title>Jonathan Eriksson</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="transition-all bg-white px-10 text-black md:px-20 lg:px-40 dark:bg-gray-800 dark:text-white snap-y snap-mandatory h-screen overflow-scroll">
                <section className="min-h-screen snap-start">
                    <nav className="py-10 mb-12 flex justify-between">
                        <h1 className="text-xl font-burtons">jotner</h1>
                        <ul className="flex items-center gap-8">
                            <li>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className="cursor-pointer text-2xl"
                                />
                            </li>
                            <li>
                                <a
                                    href="#"
                                    className="relative bg-cyan-500 font-semibold tracking-wider text-white px-4 py-2 px-4 rounded-md transition-all hover:bg-cyan-600"
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center p-10">
                        <h2 className="text-5xl py-2 text-cyan-400 font-semibold md:text-6xl">
                            Jonathan Eriksson
                        </h2>
                        <h3 className="text-xl py-2 md:text-3xl">
                            Web developer
                        </h3>
                        <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
                            Hi! I'm a web developer based in Sweden.
                        </p>
                    </div>
                    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-400 dark:text-white">
                        <a
                            href="https://github.com/jotner"
                            className="icon-rotation h-16 w-16 flex justify-center items-center relative after:absolute after:inset-0 after:border-2 after:border-gray-400 after:-z-10 after:content-[''] after:rounded-full hover:text-cyan-400 active:text-cyan-400 hover:after:rotate-[360deg] active:after:rotate-[360deg]"
                        >
                            <DiGithubAlt />
                        </a>
                        <a
                            href="#"
                            className="icon-rotation h-16 w-16 flex justify-center items-center relative after:absolute after:inset-0 after:border-2 after:border-gray-400 after:-z-10 after:content-[''] after:rounded-full hover:text-cyan-400 active:text-cyan-400 hover:after:rotate-[360deg] active:after:rotate-[360deg] p-4"
                        >
                            <FaLinkedinIn />
                        </a>
                        <a
                            href="mailto:jonathan.m.eriksson@outlook.com"
                            className="icon-rotation h-16 w-16 flex justify-center items-center relative after:absolute after:inset-0 after:border-2 after:border-gray-400 after:-z-10 after:content-[''] after:rounded-full hover:text-cyan-400 active:text-cyan-400 hover:after:rotate-[360deg] active:after:rotate-[360deg] p-3"
                        >
                            <AiOutlineMail />
                        </a>
                    </div>
                    <div className="relative mx-auto bg-gradient-to-b from-cyan-500 rounded-full h-80 w-80 mt-20 overflow-hidden md:h-96 md:w-96">
                        <Image
                            src={avatar}
                            fill
                            style={{ objectFit: 'cover' }}
                        />
                    </div>
                </section>
                <section className="min-h-screen snap-start">
                    <div className="lg:flex gap-10">
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white dark:text-black">
                            <Image
                                src={design}
                                width={100}
                                height={100}
                                className="m-auto"
                            />
                            <h3 className="text-lg font-medium pt-8 pb-2">
                                En h3
                            </h3>
                            <p className="py-2">Lorem ipsum</p>
                            <h4 className="py-4 text-teal-600">Tools</h4>
                            <p className="text-gray-800 py-1">Photoshop</p>
                            <p className="text-gray-800 py-1">Photoshop</p>
                            <p className="text-gray-800 py-1">Photoshop</p>
                        </div>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white dark:text-black">
                            <Image
                                src={code}
                                width={100}
                                height={100}
                                className="m-auto"
                            />
                            <h3 className="text-lg font-medium pt-8 pb-2">
                                En h3
                            </h3>
                            <p className="py-2">Lorem ipsum</p>
                            <h4 className="py-4 text-teal-600">Tools</h4>
                            <p className="text-gray-800 py-1">Photoshop</p>
                            <p className="text-gray-800 py-1">Photoshop</p>
                            <p className="text-gray-800 py-1">Photoshop</p>
                        </div>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white dark:text-black">
                            <Image
                                src={consulting}
                                width={100}
                                height={100}
                                className="m-auto"
                            />
                            <h3 className="text-lg font-medium pt-8 pb-2">
                                En h3
                            </h3>
                            <p className="py-2">Lorem ipsum</p>
                            <h4 className="py-4 text-teal-600">Tools</h4>
                            <p className="text-gray-800 py-1">Photoshop</p>
                            <p className="text-gray-800 py-1">Photoshop</p>
                            <p className="text-gray-800 py-1">Photoshop</p>
                        </div>
                    </div>
                </section>
                <section className="min-h-screen snap-start">
                    <div className="text-center">
                        <h3 className="text-3xl py-1">Portfolio</h3>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                            A selection of my projects
                        </p>
                    </div>
                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web1}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                                style={{ layout: 'responsive' }}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web2}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                                style={{ layout: 'responsive' }}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web3}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                                style={{ layout: 'responsive' }}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web4}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                                style={{ layout: 'responsive' }}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web5}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                                style={{ layout: 'responsive' }}
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web6}
                                className="rounded-lg object-cover"
                                width={'100%'}
                                height={'100%'}
                                style={{ layout: 'responsive' }}
                            />
                        </div>
                    </div>
                </section>
            </main>
        </div>
    )
}
